### PR TITLE
Slight grammar and related edits for README.md

### PR DESCRIPTION
**Pull request by anirudhgray**
- Corrected capitalisation for language names.
- Full stops.
- Odds and ends.

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

**Code formatting**

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by SaptakBhoumik** [comment]
@anirudhgray thank you for your contributions

**Comment by anirudhgray** [comment]
I landed up here from an article by Ethan Olchik on dev.io :)

This is really interesting stuff! Looking forward to see where this goes.

**Comment by SaptakBhoumik** [comment]
Thanks

**Comment by anirudhgray** [comment]
@SaptakBhoumik didn't want to open an issue for such a minor thing, but the "About repo" should be changed to:

> An easy to use systems programming language with Python-like syntax.

**Comment by SaptakBhoumik** [comment]
Ok I am changing it @anirudhgray

**Pull request merged**
